fix gradlew

diff --git a/fabric-1.21.4/gradlew b/fabric-1.21.4/gradlew
--- a/fabric-1.21.4/gradlew
+++ b/fabric-1.21.4/gradlew
@@ -6,9 +6,6 @@
 #
 ##############################################################################
 
-# Add default JVM options here.
-DEFAULT_JVM_OPTS='"-Xmx2g" "-Xms256m"'
-
 APP_NAME="Gradle"
 APP_BASE_NAME=`basename "$0"`
 
@@ -32,19 +29,20 @@ CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
 
 # Determine the Java command to use to start the JVM.
 if [ -n "$JAVA_HOME" ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
-        JAVACMD="$JAVA_HOME/jre/sh/java"
-    else
-        JAVACMD="$JAVA_HOME/bin/java"
-    fi
+    JAVACMD="$JAVA_HOME/bin/java"
     if [ ! -x "$JAVACMD" ] ; then
-        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
+        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
+        exit 1
     fi
 else
     JAVACMD="java"
 fi
 
-exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
+exec "$JAVACMD" \
+    -Xmx2g \
+    -Xms256m \
+    $JAVA_OPTS \
+    $GRADLE_OPTS \
     "-Dorg.gradle.appname=$APP_BASE_NAME" \
     -classpath "$CLASSPATH" \
     org.gradle.wrapper.GradleWrapperMain "$@"
